name: Testing workflow

on: workflow-dispatch

jobs:
 test-job:
 run-on: ubuntu-latest
  steps:
   - name: Hello display
     run:echo "HELLO KK FUNDA"

     -name: display the date
      run:date


